-- Example CSV loader for MySQL 8.0+
-- Replace each C:/ABSOLUTE/PATH/... placeholder with your local path.
-- Start the client with --local-infile=1 if needed.
-- Import order preserves foreign-key dependencies.

USE hospital_analytics;

LOAD DATA LOCAL INFILE 'C:/ABSOLUTE/PATH/organizations.csv'
INTO TABLE organizations
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id, @NAME, @ADDRESS, @CITY, @STATE, @ZIP)
SET
    Id = NULLIF(@Id, ''),
    NAME = NULLIF(@NAME, ''),
    ADDRESS = NULLIF(@ADDRESS, ''),
    CITY = NULLIF(@CITY, ''),
    STATE = NULLIF(@STATE, ''),
    ZIP = NULLIF(TRIM(TRAILING '\r' FROM @ZIP), '');

LOAD DATA LOCAL INFILE 'C:/ABSOLUTE/PATH/payers.csv'
INTO TABLE payers
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@Id, @NAME, @ADDRESS, @CITY, @STATE_HEADQUARTERED, @ZIP, @PHONE)
SET
    Id = NULLIF(@Id, ''),
    NAME = NULLIF(@NAME, ''),
    ADDRESS = NULLIF(@ADDRESS, ''),
    CITY = NULLIF(@CITY, ''),
    STATE_HEADQUARTERED = NULLIF(@STATE_HEADQUARTERED, ''),
    ZIP = NULLIF(@ZIP, ''),
    PHONE = NULLIF(TRIM(TRAILING '\r' FROM @PHONE), '');

LOAD DATA LOCAL INFILE 'C:/ABSOLUTE/PATH/patients.csv'
INTO TABLE patients
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @Id,
    @BIRTHDATE,
    @DEATHDATE,
    @PREFIX,
    @FIRST,
    @LAST,
    @SUFFIX,
    @MAIDEN,
    @MARITAL,
    @RACE,
    @ETHNICITY,
    @GENDER,
    @BIRTHPLACE,
    @ADDRESS,
    @CITY,
    @STATE,
    @COUNTY,
    @ZIP,
    @LAT,
    @LON
)
SET
    Id = NULLIF(@Id, ''),
    BIRTHDATE = NULLIF(@BIRTHDATE, ''),
    DEATHDATE = NULLIF(@DEATHDATE, ''),
    PREFIX = NULLIF(@PREFIX, ''),
    FIRST = NULLIF(@FIRST, ''),
    LAST = NULLIF(@LAST, ''),
    SUFFIX = NULLIF(@SUFFIX, ''),
    MAIDEN = NULLIF(@MAIDEN, ''),
    MARITAL = NULLIF(@MARITAL, ''),
    RACE = NULLIF(@RACE, ''),
    ETHNICITY = NULLIF(@ETHNICITY, ''),
    GENDER = NULLIF(@GENDER, ''),
    BIRTHPLACE = NULLIF(@BIRTHPLACE, ''),
    ADDRESS = NULLIF(@ADDRESS, ''),
    CITY = NULLIF(@CITY, ''),
    STATE = NULLIF(@STATE, ''),
    COUNTY = NULLIF(@COUNTY, ''),
    ZIP = NULLIF(@ZIP, ''),
    LAT = NULLIF(@LAT, ''),
    LON = NULLIF(TRIM(TRAILING '\r' FROM @LON), '');

LOAD DATA LOCAL INFILE 'C:/ABSOLUTE/PATH/encounters.csv'
INTO TABLE encounters
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @Id,
    @START,
    @STOP,
    @PATIENT,
    @ORGANIZATION,
    @PAYER,
    @ENCOUNTERCLASS,
    @CODE,
    @DESCRIPTION,
    @BASE_ENCOUNTER_COST,
    @TOTAL_CLAIM_COST,
    @PAYER_COVERAGE,
    @REASONCODE,
    @REASONDESCRIPTION
)
SET
    Id = NULLIF(@Id, ''),
    START = STR_TO_DATE(REPLACE(REPLACE(@START, 'T', ' '), 'Z', ''), '%Y-%m-%d %H:%i:%s'),
    STOP = STR_TO_DATE(REPLACE(REPLACE(NULLIF(@STOP, ''), 'T', ' '), 'Z', ''), '%Y-%m-%d %H:%i:%s'),
    PATIENT = NULLIF(@PATIENT, ''),
    ORGANIZATION = NULLIF(@ORGANIZATION, ''),
    PAYER = NULLIF(@PAYER, ''),
    ENCOUNTERCLASS = NULLIF(@ENCOUNTERCLASS, ''),
    CODE = NULLIF(@CODE, ''),
    DESCRIPTION = NULLIF(@DESCRIPTION, ''),
    BASE_ENCOUNTER_COST = NULLIF(@BASE_ENCOUNTER_COST, ''),
    TOTAL_CLAIM_COST = NULLIF(@TOTAL_CLAIM_COST, ''),
    PAYER_COVERAGE = NULLIF(@PAYER_COVERAGE, ''),
    REASONCODE = NULLIF(@REASONCODE, ''),
    REASONDESCRIPTION = NULLIF(TRIM(TRAILING '\r' FROM @REASONDESCRIPTION), '');

LOAD DATA LOCAL INFILE 'C:/ABSOLUTE/PATH/procedures.csv'
INTO TABLE procedures
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
    @START,
    @STOP,
    @PATIENT,
    @ENCOUNTER,
    @CODE,
    @DESCRIPTION,
    @BASE_COST,
    @REASONCODE,
    @REASONDESCRIPTION
)
SET
    START = STR_TO_DATE(REPLACE(REPLACE(@START, 'T', ' '), 'Z', ''), '%Y-%m-%d %H:%i:%s'),
    STOP = STR_TO_DATE(REPLACE(REPLACE(NULLIF(@STOP, ''), 'T', ' '), 'Z', ''), '%Y-%m-%d %H:%i:%s'),
    PATIENT = NULLIF(@PATIENT, ''),
    ENCOUNTER = NULLIF(@ENCOUNTER, ''),
    CODE = NULLIF(@CODE, ''),
    DESCRIPTION = NULLIF(@DESCRIPTION, ''),
    BASE_COST = NULLIF(@BASE_COST, ''),
    REASONCODE = NULLIF(@REASONCODE, ''),
    REASONDESCRIPTION = NULLIF(TRIM(TRAILING '\r' FROM @REASONDESCRIPTION), '');
