-- Hospital Patient SQL Analytics
-- MySQL 8.0+

CREATE DATABASE IF NOT EXISTS hospital_analytics
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE hospital_analytics;

CREATE TABLE IF NOT EXISTS organizations (
    Id VARCHAR(64) PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    ZIP VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS payers (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE_HEADQUARTERED CHAR(2),
    ZIP VARCHAR(10),
    PHONE VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS patients (
    Id CHAR(36) PRIMARY KEY,
    BIRTHDATE DATE,
    DEATHDATE DATE,
    PREFIX VARCHAR(20),
    FIRST VARCHAR(100),
    LAST VARCHAR(100),
    SUFFIX VARCHAR(20),
    MAIDEN VARCHAR(100),
    MARITAL VARCHAR(10),
    RACE VARCHAR(50),
    ETHNICITY VARCHAR(50),
    GENDER VARCHAR(10),
    BIRTHPLACE VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTY VARCHAR(100),
    ZIP VARCHAR(20),
    LAT DOUBLE,
    LON DOUBLE
);

CREATE TABLE IF NOT EXISTS encounters (
    Id CHAR(36) PRIMARY KEY,
    START DATETIME NOT NULL,
    STOP DATETIME,
    PATIENT CHAR(36) NOT NULL,
    ORGANIZATION VARCHAR(64) NOT NULL,
    PAYER CHAR(36),
    ENCOUNTERCLASS VARCHAR(50),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    BASE_ENCOUNTER_COST DECIMAL(14,2),
    TOTAL_CLAIM_COST DECIMAL(14,2),
    PAYER_COVERAGE DECIMAL(14,2),
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255),
    CONSTRAINT fk_encounter_patient
        FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    CONSTRAINT fk_encounter_organization
        FOREIGN KEY (ORGANIZATION) REFERENCES organizations(Id),
    CONSTRAINT fk_encounter_payer
        FOREIGN KEY (PAYER) REFERENCES payers(Id)
);

CREATE TABLE IF NOT EXISTS procedures (
    START DATETIME,
    STOP DATETIME,
    PATIENT CHAR(36) NOT NULL,
    ENCOUNTER CHAR(36) NOT NULL,
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    BASE_COST DECIMAL(14,2),
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255),
    CONSTRAINT fk_procedure_patient
        FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    CONSTRAINT fk_procedure_encounter
        FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
);

CREATE INDEX idx_encounters_patient_start
    ON encounters (PATIENT, START);

CREATE INDEX idx_encounters_payer
    ON encounters (PAYER);

CREATE INDEX idx_encounters_class
    ON encounters (ENCOUNTERCLASS);

CREATE INDEX idx_procedures_patient
    ON procedures (PATIENT);

CREATE INDEX idx_procedures_encounter
    ON procedures (ENCOUNTER);

CREATE INDEX idx_procedures_start
    ON procedures (START);
